version: '3.8'
services:
  api:
    build: ./app/api
    volumes:
      - ./app/api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

  web:
    build: ./app/web
    volumes:
      - ./app/web:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
