name: Build and Push Docker image

on:
  push:
    branches:
      - main  # Set this to the branch you want to build from
    paths:
      - 'openphrasebank/**' 
  workflow_dispatch:

jobs:
  build_and_push_to_docker_hub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: liuh886  # Your Docker Hub username
          password: ${{ secrets.DOCKER_API_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: liuh886/open-phrasebank:latest  # Modify if needed

